name = "Caesar"
uuid = "62eebf14-49bc-5f46-9df9-f7b7ef379406"
keywords = ["SLAM", "state-estimation", "mm-iSAM", "inference", "robotics"]
desc = "Non-Gaussian simultaneous localization and mapping"
version = "0.4.2"

[deps]
ApproxManifoldProducts = "9bbbb610-88a1-53cd-9763-118ce10c1f89"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DistributedFactorGraphs = "b5cc3c7e-6572-11e9-2517-99fb8daf2f04"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
IncrementalInference = "904591bb-b899-562f-9e6f-b8df64c7d480"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON2 = "2535ab7d-5cd8-5a07-80ac-9b1792aadce3"
KernelDensityEstimate = "2472808a-b354-52ea-a80e-1658a3c6056d"
LCMCore = "0ea44823-1ff1-5b9a-8293-5fd55a38e746"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mongoc = "4fe8b98c-fc19-5c23-8ec2-168ff83495f2"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Neo4j = "d2adbeaf-5838-5367-8a2f-e46d570981db"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RoME = "91fb55c2-4c03-5a59-ba21-f4ea956187b8"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TransformUtils = "9b8138ad-1b09-5408-aa39-e87ed6d21b63"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
Unmarshal = "cbff2730-442d-58d7-89d1-8e530c41eb02"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
ZMQ = "c2297ded-f4af-51ae-bb23-16f91089e4e1"

[compat]
ApproxManifoldProducts = "^0.1"
Combinatorics = "^0.7, 0.8, 0.9"
CoordinateTransformations = "0.5, 0.6, 0.8, 0.9"
DataStructures = "0.15, 0.16, 0.17, 0.18, 0.18, 0.19, 0.20"
DistributedFactorGraphs = "0.3, 0.4"
Distributions = "0.18, 0.19, 0.20, 0.21, 0.22, 0.23"
DocStringExtensions = "0.7, 0.8, 0.9"
FFTW = "0.2.4, 0.3, 1"
FileIO = "1"
Graphs = "0.10.2, 0.11"
ImageCore = "0.7, 0.8, 0.9"
ImageMagick = "0.7, 0.8, 0.9"
IncrementalInference = "^0.7.2"
JLD2 = "0.1, 0.2"
JSON = "0.18, 0.19, 0.20, 0.21, 0.22, 0.23"
KernelDensityEstimate = "0.5"
LCMCore = "0.5, 0.6"
Mongoc = "0.1.2, 0.2, 0.3, 0.4"
NLsolve = "3, 4"
Neo4j = "2.0"
ProgressMeter = "0.9, 1"
Reexport = "0.2"
RoME = "^0.3.4, 0.4"
Rotations = "0.11, 0.12, 0.13"
TransformUtils = "^0.2.2"
Unmarshal = "^0.2.1"
YAML = "0.3"
ZMQ = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
